/*
Copyright Ishtiaq Islam.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	crdcomv1 "github.com/ishtiaqhimel/crd-controller/pkg/apis/crd.com/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIshtiaqs implements IshtiaqInterface
type FakeIshtiaqs struct {
	Fake *FakeCrdV1
	ns   string
}

var ishtiaqsResource = schema.GroupVersionResource{Group: "crd.com", Version: "v1", Resource: "ishtiaqs"}

var ishtiaqsKind = schema.GroupVersionKind{Group: "crd.com", Version: "v1", Kind: "Ishtiaq"}

// Get takes name of the ishtiaq, and returns the corresponding ishtiaq object, and an error if there is any.
func (c *FakeIshtiaqs) Get(ctx context.Context, name string, options v1.GetOptions) (result *crdcomv1.Ishtiaq, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ishtiaqsResource, c.ns, name), &crdcomv1.Ishtiaq{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdcomv1.Ishtiaq), err
}

// List takes label and field selectors, and returns the list of Ishtiaqs that match those selectors.
func (c *FakeIshtiaqs) List(ctx context.Context, opts v1.ListOptions) (result *crdcomv1.IshtiaqList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ishtiaqsResource, ishtiaqsKind, c.ns, opts), &crdcomv1.IshtiaqList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &crdcomv1.IshtiaqList{ListMeta: obj.(*crdcomv1.IshtiaqList).ListMeta}
	for _, item := range obj.(*crdcomv1.IshtiaqList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ishtiaqs.
func (c *FakeIshtiaqs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ishtiaqsResource, c.ns, opts))

}

// Create takes the representation of a ishtiaq and creates it.  Returns the server's representation of the ishtiaq, and an error, if there is any.
func (c *FakeIshtiaqs) Create(ctx context.Context, ishtiaq *crdcomv1.Ishtiaq, opts v1.CreateOptions) (result *crdcomv1.Ishtiaq, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ishtiaqsResource, c.ns, ishtiaq), &crdcomv1.Ishtiaq{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdcomv1.Ishtiaq), err
}

// Update takes the representation of a ishtiaq and updates it. Returns the server's representation of the ishtiaq, and an error, if there is any.
func (c *FakeIshtiaqs) Update(ctx context.Context, ishtiaq *crdcomv1.Ishtiaq, opts v1.UpdateOptions) (result *crdcomv1.Ishtiaq, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ishtiaqsResource, c.ns, ishtiaq), &crdcomv1.Ishtiaq{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdcomv1.Ishtiaq), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIshtiaqs) UpdateStatus(ctx context.Context, ishtiaq *crdcomv1.Ishtiaq, opts v1.UpdateOptions) (*crdcomv1.Ishtiaq, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ishtiaqsResource, "status", c.ns, ishtiaq), &crdcomv1.Ishtiaq{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdcomv1.Ishtiaq), err
}

// Delete takes name of the ishtiaq and deletes it. Returns an error if one occurs.
func (c *FakeIshtiaqs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(ishtiaqsResource, c.ns, name, opts), &crdcomv1.Ishtiaq{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIshtiaqs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ishtiaqsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &crdcomv1.IshtiaqList{})
	return err
}

// Patch applies the patch and returns the patched ishtiaq.
func (c *FakeIshtiaqs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *crdcomv1.Ishtiaq, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ishtiaqsResource, c.ns, name, pt, data, subresources...), &crdcomv1.Ishtiaq{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdcomv1.Ishtiaq), err
}
